### PR TITLE
clarifications as suggested in #170 and w3c/json-ld-wg#85

### PR DESCRIPTION
**Pull request by pchampin**
as per my action

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/193.html" title="Last updated on Jun 13, 2019, 4:22 PM UTC (6ea443e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/193/c13919d...6ea443e.html" title="Last updated on Jun 13, 2019, 4:22 PM UTC (6ea443e)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
I have just a minor comment: the text includes the text:

> However, all URIs starting with  http://www.w3.org/ns/json-ld  are reserved for future use by JSON-LD specifications. 

A "Note" is automatically non normative. I wonder whether it would not be better to move this text into the 'normative' text, right after the list of json-ld URI-s (and probably without the word 'However').

Otherwise it looks o.k. to me.

**Comment by BigBlueHat** [comment]
Also, @pchampin I think you want us added as "reviewers" not "assignee's" (you would be the assignee for this one. 😃

**Comment by pchampin** [comment]
@bigbluehat indeed I did. Sorry about that...

**Comment by BigBlueHat** [comment]
> @BigBlueHat indeed I did. Sorry about that...

No worries! 😄

**Pull request merged**
