### PR TITLE
typo fixes

### PR DESCRIPTION
**Pull request by steltenpower**
***
<a href="https://pr-preview.s3.amazonaws.com/steltenpower/json-ld-syntax/pull/352.html" title="Last updated on May 10, 2020, 1:36 AM UTC (6ef73ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/352/4c103ea...steltenpower:6ef73ee.html" title="Last updated on May 10, 2020, 1:36 AM UTC (6ef73ee)">Diff</a>

### CODE REVIEW

**Comment by gkellogg** [comment]
@iherman didn't these checks look to see if the submitter was in the organization, or allow it to be overridden? That seems to be missing from checks now. Certainly, there shouldn't be any issue with this PR, but it's curious that it's not doing that check anymore.

**Comment by iherman** [comment]
@gkellogg you are right, I will ask...

**Comment by plehegar** [comment]
there is a glitch on GH side apparently. Our repo-manager got properly invoked and has https://labs.w3.org/repo-manager/pr/id/w3c/json-ld-syntax/352 . @dontcallmedom is following up.

**Comment by iherman** [comment]
@gkellogg all the changes are really spelling errors; they can be incorporated into the final Rec. Meaning that it may not be necessary to store them as Errata for the errata management.

**Comment by gkellogg** [comment]
> @gkellogg all the changes are really spelling errors; they can be incorporated into the final Rec. Meaning that it may not be necessary to store them as Errata for the errata management.

Yes, but I thought it would be a good test of the errata system. As I understand it, this should now show up in https://w3c.github.com/json-ld-syntax/errata, although I don't see it there.

Once merged, we can remove the labels, as it would no longer need to be listed.

**Comment by iherman** [comment]
> Yes, but I thought it would be a good test of the errata system. As I understand it, this should now show up in https://w3c.github.com/json-ld-syntax/errata, although I don't see it there.

Nop. The errata list only includes "accepted" errata, meaning that the label is set to "Errata". "ErratumRaised" does not mean it is an accepted erratum.

**Pull request merged**
