### PR TITLE
Updates for ECHIDNA:

### PR DESCRIPTION
**Pull request by gkellogg**
# **Not ready for merge**

* Requires token be generated and updated in .travis.yml.
* Publication happens when pushed to "publications" branch.
* Requires URL to WG Decision from meeting minutes.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/65.html" title="Last updated on Sep 17, 2018, 8:29 PM GMT (488f215)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/65/a7faf5b...488f215.html" title="Last updated on Sep 17, 2018, 8:29 PM GMT (488f215)">Diff</a>

### CODE REVIEW

**Comment by gkellogg** [comment]
@iherman we'll need to get tokens for all three specs (just trying Syntax for now).

@BigBlueHat and @azaroth42 We'll need a WG decision to point to.

Travis configuration may need some debugging, but this will cause publication via ENCHIDNA only on branch "publications" after other Travis steps have completed.

**Comment by gkellogg** [comment]
One thought is to run a link-checker docker image as a build step. I experimented with the following:

    docker run stupchiy/checklink http://w3.org/TR/json-ld11

Problem is, it can't run against a local file. We could consider running a separate docker image with a web server to serve up index.html, or we could run it against the w3c service, but I'd be concerned if we might run into throttling issues.

    docker run stupchiy/checklink  https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/json-ld-syntax/?specStatus=WD;shortName=json-ld11

**Comment by ajs6f** [comment]
@gkellogg, to my naive inspection, it looks like that Docker image is running W3C's [`link-checker`](https://github.com/w3c/link-checker/). I just checked, and `link-checker` can run fine on local files. Maybe we can just use our `.travis.yml` to install `link-checker` directly to our Travis VM? It's just a Perl module, and `perl -MCPAN -e 'install W3C::LinkChecker'` did fine for me.

**Comment by gkellogg** [comment]
@ajs6f, good to know. Interesting, then, that the docker image doesn’t. I’ll play with that.

**Comment by gkellogg** [comment]
The workflow is based on [How to use Echidna with ReSpec and GitHub](https://github.com/w3c/echidna/wiki/How-to-use-Echidna-with-ReSpec-and-GitHub).

**Comment by gkellogg** [comment]
The last thing to do is to remove the "dry-run" configuration, which we can do after the first time pushing to the "publications" branch to verify it's working properly without doing a dry run.

Also, it will be cleaner to do a "Squash and merge", which I can take care of.

**Pull request merged**
