### PR TITLE
Test PR Preview

### PR DESCRIPTION
**Pull request by gkellogg**
**Don't merge this.**

Creates a minimal index.html without any pubsubhub integrations to see if PR Preview will wake up.

### CODE REVIEW

**Comment by gkellogg** [comment]
Still not there, but it could be possible that the diff stage is holding it up, as it is accessing the existing state of the repo. How to know?

cc/ @iherman

**Comment by iherman** [comment]
To be honest, I am without a clue. Although not really in the purview of our system team, we may still ask for help because there may be some experiences with this type of problems.

@deniak @tripu @plehegar : in short, help:-) The PR preview has ceased to work on the documents on this repo, and we are trying to find out why. I know Tobie does not maintain this code any more, but is there a way to get hold of error messages/reports that give us an idea as for why the system does not work? We could try to take it from there...

**Comment by deniak** [comment]
Unfortunately, pr-preview is hosted on a server outside W3C and I don't have access to its logs. If @tobie is not maintaining the service anymore, someone has to take over.

I tried to see if there was a problem during the generation with spec-generator and it worked fine. Same thing for html diff so the problem must be coming from somewhere else.

**Comment by gkellogg** [comment]
@tobie the issue isn’t setup, it’s visibility into what went wrong. It was working properly for many PRs until it just stopped working; bother here, on json-ld-api and json-ld-framing. Presumably, there’s something in a log file that might give a clue to what’s going on, but we have no visibility into to these. Short of giving us an idea of why it stopped working, some form of console that could show the status re different repos would be useful for many, I suspect.

I sympathize with the burden support gives you, but this has rapidly become a required tool for WGs to reply upon, and if not you, then perhaps @deniak or someone in W3C can step in.

**Comment by tobie** [comment]
There are limitations to what the logs provide (they’re only available 24h) that makes it suboptimal as a debugging strategy. The real solution is surfacing

**Comment by tobie** [comment]
That said, I’m happy to give @deniak log access. It mostly won’t solve your problem, though.

**Comment by tobie** [comment]
Alright, so I unfortunately can't give you log access without upgrading to a paid plan. Here's the error message I'm seeing:

```
w3c/json-ld-syntax/74: opened (Error: 500 Internal Server Error) 
Oct 01 16:27:16 pr-preview app/web.1:  { error: '\n?  Sorry, there was an error generating the HTML. Please report this issue!\n\u001b[36mSpecification: https://cdn.rawgit.com/w3c/json-ld-syntax/eb61149c86124d4a53ec01f16cd8db132201ad44/index.html?isPreview=true;publishDate=2018-10-01\u001b[39m\n\u001b[36mReSpec version: 23.0.5\u001b[39m\n\u001b[36mFile a bug: https://github.com/w3c/respec/\u001b[39m\n\u001b[36mError: Error: Evaluation failed: undefined\u001b[39m\n\u001b[36m\u001b[39m', 
Oct 01 16:27:16 pr-preview app/web.1:    request_url: 'https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fcdn.rawgit.com%2Fw3c%2Fjson-ld-syntax%2Feb61149c86124d4a53ec01f16cd8db132201ad44%2Findex.html%3FisPreview%3Dtrue' } 
``` 

Seems like spec-generator is acting up, see:

https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fcdn.rawgit.com%2Fw3c%2Fjson-ld-syntax%2Feb61149c86124d4a53ec01f16cd8db132201ad44%2Findex.html%3FisPreview%3Dtrue

I still maintain that the path going forward is to surface these errors properly in the UI. Again, I'm happy to take a PR for it, or to undertake this work for a fee if no one is willing to do it.

PR Preview is used by folks outside of W3C, so I can't just transfer the project over to W3C. That said, if W3C wants to run its own instance, PR Preview is OSS, so this option is also on the table.

**Comment by deniak** [comment]
@tobie thanks for the logs. It appears the issue comes from respec, I'll raise an issue. @gkellogg I'm following up with Marcos. Hopefully it'll be fixed soon.

I'll try to find time to work on the error feedback and will submit a PR.

**Comment by gkellogg** [comment]
Thanks for your help, @deniak. Marcos has a change to ReSpec which should help keep PR Preview keep running in the face of such errors, but surface them.

**Pull request closed without merging**
